---
- name: Configure Development Box
  vars:
    ansible_ssh_user: ubuntu
    ansible_ssh_port: 2424
    ansible_ssh_private_key_file: "{{ playbook_dir }}/.vagrant/machines/default/virtualbox/private_key"
  hosts: default
  remote_user: vagrant
  become: True
  roles:
    - base
    - { role: docker, docker_compose_version: 1.15.0 }
    - nginx
    - { role: prometheus, prometheus_version: 2.0.0, vm_private_ip: 127.0.0.1 }
    - { role: node_exporter, node_exporter_version: 0.15.1 }
    - { role: alertmanager, alertmanager_version: 0.10.0, vm_private_ip: 127.0.0.1 }
    - cadvisor
    - grafana
