groups:
- name: example
  rules:
  - alert: containerMissing
    expr: absent(((time() - container_last_seen{name="nginx"}) < 5))
    for: 5s
    labels:
      severity: page
    annotations:
      summary: Instance {{$labels.instance}} down
  - alert: containerSpinLoop
    expr: container_start_time_seconds{name="nginx"} < 5
    for: 10s
    labels:
      severity: page
    annotations:
      summary: Instance {{$labels.instance}} stuck in restart loop
  - alert: DiskWillFillIn4Hours
    expr: predict_linear(node_filesystem_free{job='node',mountpoint='/'}[1h], 4*3600) < 0
    for: 5m
    labels:
      severity: page
    annotations:
      summary: Instance {{$labels.instance}} disk will fill in 4 hours
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: page
    annotations:
      summary: Instance {{ $labels.instance }} down
  - alert: high_cpu_load
    expr: node_load1 > 1.5
    for: 30s
    labels:
      severity: page
    annotations:
      summary: Server under high load
  - alert: high_memory_load
    expr: (sum(node_memory_MemTotal) - sum(node_memory_MemFree + node_memory_Buffers + node_memory_Cached) ) / sum(node_memory_MemTotal) * 100 > 85
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: Server memory is almost full
