global:
    scrape_interval: 1m
    evaluation_interval: 1m
    external_labels:
        monitor: 'my-monitor'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'node-exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9100']
